<?php

namespace TdS\MuseeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
}