<?php

namespace TdS\MuseeBundle\Repository;

use Doctrine\ORM\EntityRepository;



/**
 * MontagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontagneRepository extends EntityRepository{

	


	public function find3random(){
	    $queryBuilder = $this->createQueryBuilder('a');

	    $queryBuilder
	    	// ->select('i, RAND() AS HIDDEN r')
    		// ->from('TdSMuseeBundle:Montagne', 'i')
    		// ->orderBy('r', 'ASC')
    		->setMaxResults(3);
	    // On récupère la Query à partir du QueryBuilder
	    $query = $queryBuilder->getQuery();

	    // On récupère les résultats à partir de la Query
	    $results = $query->getResult();

	    // On retourne ces résultats
	    return $results;

	}
}
