<?php

namespace TdS\MuseeBundle\Repository;

/**
 * ReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglementRepository extends \Doctrine\ORM\EntityRepository
{
}
